pybonjour: dont close the sdref from callback
this caused errors like:

Traceback (most recent call last):
  File "/home/machinekit/machinekit-future/lib/python/hal_glib.py", line 303, in bonjour_readable
    callback(sdref)
  File "/usr/local/lib/python2.7/dist-packages/pybonjour-1.1.1-py2.7.egg/pybonjour.py", line 896, in
    _DNSServiceProcessResult(sdRef)
  File "/usr/local/lib/python2.7/dist-packages/pybonjour-1.1.1-py2.7.egg/pybonjour.py", line 286, in _errcheck
    raise cls(result)
pybonjour.BonjourError: (-65540, 'bad param')

and

shutdown here
mah@vbox-wheezy:~/linuxcnc/src/hal/haltalk/examples$ gladevcp -E motorctrl.ui
python: compat.c:491: DNSServiceProcessResult: Assertion `__ret == 0' failed.
Aborted (core dumped)